name: anaconda_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - expat=2.6.2
  - libffi=3.4.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.12.4
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aioftp==0.22.3
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.2
      - aiosignal==1.3.1
      - astropy==6.1.2
      - astropy-iers-data==0.2024.8.5.0.32.23
      - attrs==24.2.0
      - blinker==1.8.2
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - flask==3.0.3
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - idna==3.7
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.1.post1
      - multidict==6.0.5
      - numpy==2.0.1
      - opencv-python==4.10.0.84
      - packaging==24.1
      - parfive==2.1.0
      - pillow==10.4.0
      - pyerfa==2.0.1.4
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.14.0
      - six==1.16.0
      - sunpy==6.0.0
      - tqdm==4.66.5
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - yarl==1.9.4
